const fs = require('fs');

// List of domains to block
const domains = [
  'adtago.s3.amazonaws.com',
  'analyticsengine.s3.amazonaws.com',
  'analytics.s3.amazonaws.com',
  'advice-ads.s3.amazonaws.com',
  'pagead2.googlesyndication.com',
  'adservice.google.com',
  'pagead2.googleadservices.com',
  'stats.g.doubleclick.net',
  'ad.doubleclick.net',
  'static.doubleclick.net',
  'm.doubleclick.net',
  'mediavisor.doubleclick.net',
  'ads30.adcolony.com',
  'adc3-launch.adcolony.com',
  'events3alt.adcolony.com',
  'wd.adcolony.com',
  'static.media.net',
  'media.net',
  'adservetx.media.net',
  'analytics.google.com',
  'click.googleanalytics.com',
  'google-analytics.com',
  'ssl.google-analytics.com',
  'mouseflow.com',
  'cdn.mouseflow.com',
  '02.mouseflow.com',
  '0g.mouseflow.com',
  'api.mouseflow.com',
  'tools.mouseflow.com',
  'cdn-test.mouseflow.com',
  'luckyorange.com',
  'api.luckyorange.com',
  'realtime.luckyorange.com',
  'cdn.luckyorange.com',
  'w1.luckyorange.com',
  'upload.luckyorange.net',
  'cs.luckyorange.net',
  'settings.luckyorange.net',
  'adm.horjar.com',
  'identify.hotjar.com',
  'insights.hotjar.com',
  'script.hotjar.com',
  'surveys.hotjar.com',
  'careers.hotjar.com',
  'events.hotjar.io',
  'freshmarketer.com',
  'clarity.freshmarketer.com',
  'fwtacks.freshmarketer.com',
  'stats.wp.com',
  'notify.bugsnag.com',
  'sessions.bugsnag.com',
  'api.bugsnag.com',
  'app.bugsnag.com',
  'browser.sentrycdn.com',
  'app.getsentry.com',
  'pixel.facebook.com',
  'sn.fb.facebook.com',
  'static.ads-twitter.com',
  'ads-api.twitter.com',
  'ads.linkedin.com',
  'analytics.pointdrive.linkedin.com',
  'ads.pinterest.com',
  'log.pinterest.com',
  'analytics.pinterest.com',
  'trk.pinterest.com',
  'events.reddit.com',
  'events.redditmedia.com',
  'ads-api.tiktok.com',
  'analytics.tiktok.com',
  'ads-sg.tiktok.com',
  'analytics-sg.tiktok.com',
  'business-api.tiktok.com',
  'cs.tiktok.com',
  'log.byteoversea.com',
  'ads.youtube.com',
  'ads.yahoo.com',
  'analytics.yahoo.com',
  'geo.yahoo.com',
  'ud.yahoo.com',
  'udcm.yahoo.com',
  'analytics.query.yahoo.com',
  'partnerads.ysm.yahoo.com',
  'log.rc.yahoo.com',
  'gemini.yahoo.com',
  'adtech.yahooinc.com',
  'extmaps-api.yandex.net',
  'offerwall.yandex.net',
  'adfox.yandex.ru',
  'appmetrica.yandex.ru',
  'adstat.yandex.ru',
  'metrika.yandex.ru',
  'auction.unityads.unity3d.com',
  'webview.unityads.unity3d.com',
  'config.unityads.unity3d.com',
  'adserver.unityads.unity3d.com',
  'iot-eu-logger.realme.com',
  'iot-logger.realme.com',
  'bdapi-ads.realmemobile.com',
  'bdapi-in-ads.realmemobile.com',
  'adfs.oppomobile.com',
  'adx.ads.oppomobile.com',
  'ck.ads.oppomobile.com',
  'data.ads.oppomobile.com',
  'click.oneplus.cn',
  'open.oneplus.net',
  'iadsdk.apple.com',
  'metrics.icloud.com',
  'metrics.mzstatic.com',
  'api-adservices.apple.com',
  'books-analytics-events.apple.com',
  'weather-analytics-events.apple.com',
  'notes-analytics-events.apple.com',
  'metrics.data.hicloud.com',
  'metrics2.data.hicloud.com',
  'grs.hicloud.com',
  'logservice.hicloud.com',
  'logservice1.hicloud.com',
  'logbak.hicloud.com',
  'samsungads.com',
  'metrics.samsung.com',
  'nm1.metrics.samsung.com',
  'samsung.com.112.2o7.net',
  'analytics-api.samsunghealthcn.com',
  'iot-eu-logser.realme.com',
  'iot-logser.realme.com',
  'data.mistat.xiaomi.com',
  'data.mistat.india.xiaomi.com',
  'data.mistat.rus.xiaomi.com',
  'tracking.rus.miui.com',
  'adsfs.oppomobile.com',
  'log.fc.yahoo.com',
  'adfstat.yandex.ru',
  'ads.tiktok.com',
  'an.facebook.com',
  'afs.googlesyndication.com'
];

// Generate rules
const rules = domains.map((domain, index) => ({
  id: index + 1,
  priority: 1,
  action: {
    type: "block"
  },
  condition: {
    urlFilter: `||${domain}^`,
    resourceTypes: ["main_frame", "sub_frame", "script", "xmlhttprequest", "image", "media"]
  }
}));

// Write rules to rules.json
fs.writeFileSync('rules.json', JSON.stringify(rules, null, 2), 'utf8');
console.log('rules.json has been generated successfully.');